# Generated by Django 5.1.7 on 2025-03-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=300)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.CharField(blank=True, max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
