# Generated by Django 5.1.7 on 2025-03-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categoria',
            field=models.CharField(choices=[('Musica', 'Musica'), ('Palestra', 'Palestra'), ('Workshop', 'Workshop')], max_length=200),
        ),
    ]
